
{% if @('app.build') == 'static' %}
FROM {{ @('namespace') }}_console:latest as console
{% endif %}

FROM node:10-alpine

RUN npm install pm2 -g

{% if @('app.build') == 'static' %}
COPY --from=console /app /app
{% else %}
VOLUME /app
{% endif %}

USER node

WORKDIR /app
CMD ["pm2", "start", "apps.json"]
